CREATE TABLE AuditLog (
    log_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    table_name VARCHAR(50) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    record_id TEXT, -- Storing ID as text to handle different types (int, string for class_name)
    changed_by VARCHAR(50) DEFAULT CURRENT_ROLE,
    username VARCHAR(50) DEFAULT current_setting('app.current_username', true),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details TEXT -- Optional: store what changed
);
