CREATE TABLE Users(
    user_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(60) NOT NULL UNIQUE CHECK (email ~ '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'),
    password TEXT NOT NULL --hash
);
CREATE TABLE Roles(
    role_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    role_name VARCHAR(10) UNIQUE NOT NULL,
    role_desc TEXT
);
CREATE TABLE UserRole(
    user_id INT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
    role_id INT NOT NULL REFERENCES Roles(role_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
CREATE TABLE AuditLog (
    log_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    table_name VARCHAR(50) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    record_id TEXT, -- Storing ID as text to handle different types (int, string for class_name)
    changed_by VARCHAR(50) DEFAULT CURRENT_ROLE,
    username VARCHAR(50) DEFAULT current_setting('app.current_username', true), -- Uses the session variable set by bouncer
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    details TEXT -- Optional: store what changed
);
CREATE TABLE Teacher(
    teacher_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    teacher_name VARCHAR(50) NOT NULL,
    teacher_surname VARCHAR(50) NOT NULL,
    teacher_patronym VARCHAR(50) NULL, --для закордонних вчителів
    teacher_phone VARCHAR(20) NOT NULL UNIQUE CHECK ( teacher_phone ~ '^0[3-9]\d{1}-\d{3}-\d{4}$'),
    teacher_user_id INT UNIQUE REFERENCES Users(user_id) ON DELETE SET NULL
);
CREATE TABLE Subjects(
    subject_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    subject_name TEXT NOT NULL UNIQUE,
    cabinet INT NOT NULL DEFAULT 100 CHECK (cabinet > 99 AND cabinet < 399),
    subject_program TEXT --for now null
);
CREATE TABLE Material(
    material_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    material_name VARCHAR(100) NOT NULL, --без спаму
    material_desc TEXT,
    material_link TEXT UNIQUE
);
CREATE TYPE journal_status_enum AS ENUM ('Присутній', 'П', 'Не присутній', 'Н');
CREATE TABLE Journal(
    journal_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    journal_teacher INT REFERENCES Teacher(teacher_id) ON DELETE SET NULL,
    journal_name VARCHAR(50)
);
CREATE TABLE Days(
    day_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day_subject INT NOT NULL REFERENCES Subjects(subject_id), 
    day_time TIME NOT NULL,
    day_weekday VARCHAR(20) CHECK ( day_weekday IN ('Понеділок', 'Вівторок', 'Середа', 'Четвер', 'П’ятниця')),
    day_timetable INT REFERENCES Timetable(timetable_id) ON DELETE CASCADE
);
CREATE TABLE Class(
    class_name VARCHAR(10) PRIMARY KEY CHECK ( class_name ~ '^(?:[1-9]|1[0-2])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$'),
    class_journal_id INT REFERENCES Journal(journal_id) ON DELETE SET NULL,
    class_mainTeacher INT UNIQUE REFERENCES Teacher(teacher_id) ON DELETE SET NULL
);
CREATE TABLE Timetable(
    timetable_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timetable_name VARCHAR(20) NOT NULL UNIQUE,
    timetable_class VARCHAR(10) UNIQUE NOT NULL REFERENCES Class(class_name) CHECK ( timetable_class ~ '^(?:[1-9]|1[0-2])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$') ON DELETE CASCADE
);
CREATE TABLE Lessons(
    lesson_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    lesson_name VARCHAR(50) NOT NULL,
    lesson_class VARCHAR(10) NOT NULL REFERENCES Class(class_name) CHECK ( lesson_class ~ '^(?:[1-9]|1[0-2])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$') ON DELETE CASCADE,
    lesson_subject INT NOT NULL REFERENCES Subjects(subject_id),
    lesson_material INT REFERENCES Material(material_id),
    lesson_teacher INT NOT NULL REFERENCES Teacher(teacher_id),
    lesson_date DATE DEFAULT CURRENT_DATE NOT NULL,
    UNIQUE (lesson_name, lesson_teacher),
    UNIQUE (lesson_class, lesson_subject, lesson_date, lesson_teacher)
);
CREATE TABLE Homework(
    homework_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    homework_name VARCHAR(100),
    homework_teacher INT REFERENCES Teacher(teacher_id) ON DELETE SET NULL,
    homework_lesson INT NOT NULL REFERENCES Lessons(lesson_id) ON DELETE CASCADE,
    homework_duedate DATE NOT NULL,
    homework_created_at DATE DEFAULT CURRENT_DATE NOT NULL,
    homework_desc TEXT NOT NULL,
    homework_class VARCHAR(10) NOT NULL REFERENCES Class(class_name) CHECK ( homework_class ~ '^(?:[1-9]|1[0-2])-([А-ЩЬЮЯҐЄІЇ]|[а-щьюяґєії])$') ON DELETE CASCADE
);
CREATE TABLE Students(
    student_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    student_name VARCHAR(50) NOT NULL,
    student_surname VARCHAR(50) NOT NULL,
    student_patronym VARCHAR(50) NULL,
    student_phone VARCHAR(20) NOT NULL UNIQUE CHECK ( student_phone ~ '^0[3-9]\d{1}-\d{3}-\d{4}$'),
    student_user_id INT UNIQUE REFERENCES Users(user_id) ON DELETE SET NULL, 
    student_class VARCHAR(10) REFERENCES Class(class_name) ON DELETE SET NULL
);
CREATE TABLE Parents(
    parent_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parent_name VARCHAR(50) NOT NULL,
    parent_surname VARCHAR(50) NOT NULL,
    parent_patronym VARCHAR(50) NULL,
    parent_phone VARCHAR(20) NOT NULL UNIQUE,
    parent_user_id INT UNIQUE REFERENCES Users(user_id) ON DELETE SET NULL
);
CREATE TABLE StudentParent (
    student_id_ref INT REFERENCES Students(student_id) ON DELETE CASCADE,
    parent_id_ref INT REFERENCES Parents(parent_id) ON DELETE CASCADE,
    PRIMARY KEY (student_id_ref, parent_id_ref)
);
CREATE TABLE StudentData(
    data_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    journal_id INT NOT NULL REFERENCES Journal(journal_id) ON DELETE CASCADE,
    student_id INT NOT NULL REFERENCES Students(student_id) ON DELETE CASCADE,
    lesson INT NOT NULL REFERENCES Lessons(lesson_id) ON DELETE CASCADE,
    mark SMALLINT NULL CHECK (mark >= 1 AND mark <= 12), --шкільна 12-ти бальна система
    status journal_status_enum NOT NULL,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
